# This file contains the credentials for the voice & chat platforms
# which your bot is using.
# https://rasa.com/docs/rasa/user-guide/messaging-and-voice-channels/

rest:
#  # you don't need to provide anything here - this channel doesn't
#  # require any credentials


#facebook:
#  verify: "<verify>"
#  secret: "<your secret>"
#  page-access-token: "<your page access token>"

#slack:
#  slack_token: "<your slack token>"
#  slack_channel: "<the slack channel>"

#socketio:
#  user_message_evt: <event name for user message>
#  bot_message_evt: <event name for but messages>
#  session_persistence: <true/false>

#mattermost:
#  url: "https://<mattermost instance>/api/v4"
#  team: "<mattermost team>"
#  user: "<bot username>"
#  pw: "<bot token>"
#  webhook_url: "<callback URL>"

rasa:
  url: "http://localhost:5002/api"

socketio:
  user_message_evt: user_uttered
  bot_message_evt: bot_uttered
  session_persistence: true

facebook:
  verify: "rasa-chatbot"
  secret: "b33a969bf90f8ca570114fd42b672b15"
  page-access-token: "EAAC44rRTGDIBAEqGH13Eo60ZAso91XW8IwM28PK86bHw0W5zFWwQi1jrlAZAlsZAuG7geA9dRLZBFhZBVlIp5Bt9T61PAfcWeqYG5TBoIac1kB4CmjnjCXkLAw7MCncxnZCvVMA1CUROvbUXRXxkAobu0ykyPQpqC44EZCNzL9JOT3tYCMUz5aT"